/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.3.1/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    id ("it.filippor.p2") version "0.0.3"
}

repositories {
	//mavenLocal()
    //mavenCentral()
}


dependencies {
    p2frameworkBundles("org.eclipse.platform:org.eclipse.core.runtime:+") {exclude(module = "org.eclipse.osgi")}
}


p2.doLastOnFramework(tasks.register("hello"), {_,sp->
	println(sp.getService(it.filippor.p2.api.P2RepositoryManager::class.java))
}) 
