{
  "formatVersion": "1.1",
  "component": {
    "group": "it.filippor.p2",
    "module": "p2impl",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "p2impl-0.0.4.jar",
          "url": "p2impl-0.0.4.jar",
          "size": 20909,
          "sha512": "f0b4a0dd97ca3fa932e9dd27f8c915a3b26dc2eb5ac68bdf9c9dbc1c073cbc39259d3f17a4c3443fffc045b9204533d0097ce74f98ba7b61dee78beaedd750c7",
          "sha256": "68f1bfbf3ca17b7d065735e5d748f81e86fdeb8db28658675332012bca87a232",
          "sha1": "c43038816e5c27df642a96d332a1d7e975288160",
          "md5": "fbafebfdd0c2e9fa43cd7ba6ede74fb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.common",
          "version": {
            "requires": "3.15.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.director",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.engine",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.metadata.repository",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.operations",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.publisher",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "org.eclipse.osgi"
            }
          ]
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.publisher.eclipse",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.repository",
          "version": {
            "requires": "2.5.100"
          }
        },
        {
          "group": "org.eclipse.ecf",
          "module": "org.apache.commons.codec",
          "version": {
            "requires": "1.9.0.v20170208-1614"
          }
        },
        {
          "group": "org.eclipse.ecf",
          "module": "org.apache.commons.logging",
          "version": {
            "requires": "1.1.1.v201101211721"
          }
        },
        {
          "group": "org.eclipse.ecf",
          "module": "org.apache.httpcomponents.httpclient",
          "version": {
            "requires": "4.5.2.v20170210-0925"
          }
        },
        {
          "group": "org.eclipse.ecf",
          "module": "org.apache.httpcomponents.httpcore",
          "version": {
            "requires": "4.4.6.v20170210-0925"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.core.net",
          "version": {
            "requires": "1.3.1100"
          },
          "excludes": [
            {
              "group": "*",
              "module": "org.eclipse.osgi"
            }
          ]
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.core.runtime",
          "version": {
            "requires": "3.22.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "org.eclipse.osgi"
            }
          ]
        },
        {
          "group": "org.eclipse.ecf",
          "module": "org.eclipse.ecf.identity",
          "version": {
            "requires": "3.9.402"
          }
        },
        {
          "group": "org.eclipse.ecf",
          "module": "org.eclipse.ecf.provider.filetransfer.httpclient45",
          "version": {
            "requires": "1.0.401"
          }
        },
        {
          "group": "org.eclipse.ecf",
          "module": "org.eclipse.ecf.provider.filetransfer.ssl",
          "version": {
            "requires": "1.0.201"
          }
        },
        {
          "group": "org.eclipse.ecf",
          "module": "org.eclipse.ecf.ssl",
          "version": {
            "requires": "1.2.401"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.concurrent",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.frameworkadmin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.frameworkadmin.equinox",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.launcher",
          "version": {
            "requires": "1.6.200"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.director.app",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.garbagecollector",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.jarprocessor",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.artifact.repository",
          "version": {
            "requires": "1.4.100"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.touchpoint.eclipse",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.touchpoint.natives",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.p2.transport.ecf",
          "version": {
            "requires": "1.3.100"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.simpleconfigurator",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.simpleconfigurator.manipulator",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.osgi.compatibility.state",
          "version": {
            "requires": "1.2.400"
          },
          "excludes": [
            {
              "group": "*",
              "module": "org.eclipse.osgi"
            }
          ]
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.osgi.services",
          "version": {
            "requires": "3.10.100"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.osgi.util",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.eclipse.tycho",
          "module": "org.eclipse.tycho.noopsecurity",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.equinox.ds",
          "version": {
            "requires": "1.6.200"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.65.01"
          }
        }
      ],
      "files": [
        {
          "name": "p2impl-0.0.4.jar",
          "url": "p2impl-0.0.4.jar",
          "size": 20909,
          "sha512": "f0b4a0dd97ca3fa932e9dd27f8c915a3b26dc2eb5ac68bdf9c9dbc1c073cbc39259d3f17a4c3443fffc045b9204533d0097ce74f98ba7b61dee78beaedd750c7",
          "sha256": "68f1bfbf3ca17b7d065735e5d748f81e86fdeb8db28658675332012bca87a232",
          "sha1": "c43038816e5c27df642a96d332a1d7e975288160",
          "md5": "fbafebfdd0c2e9fa43cd7ba6ede74fb6"
        }
      ]
    }
  ]
}
