/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.3.1/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    id ("java-library")
    id ("it.filippor.p2") version ( "0.0.1")
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}
p2.setUpdateSites( mutableListOf(
                uri("http://download.eclipse.org/releases/2019-03"),
                uri("http://download.eclipse.org/releases/2019-06")))

p2.publishTask("p2publish") {
     setRepo(buildDir.toPath().resolve("targetSite").toUri())
     setBundles(configurations.getByName("runtime"))
   }

dependencies {
  api(p2.bundles(false, "org.eclipse.core.resources:[3.13,3.14)"))
  compile(project(path = ":p2testNested"))
}
