/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package p2Gradle;

import org.eclipse.swtbot.eclipse.finder.SWTBotInfo;

public class Library {

    public boolean someLibraryMethod() {

        SWTBotInfo.printInfo();
        return true;
    }
}
