{
  "formatVersion": "1.1",
  "component": {
    "group": "it.filippor.p2",
    "module": "p2api",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.osgi",
          "module": "osgi.core",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "p2api-0.0.4.jar",
          "url": "p2api-0.0.4.jar",
          "size": 3912,
          "sha512": "d0617b2c5f28b8712f93ba683a6729b61dd675fb07ca8c4e9ff8a14c68f32d2d06d66591576221a663cf9b021aa0864aff44cab65674e2c8dfcc2f836e0a4bbd",
          "sha256": "9a306a5bd7057204c92fb1af6606e82cd249b3aa058fd1f7514ae03337953a16",
          "sha1": "1d88a2fec9d351882872c94fd1edbd4f72128056",
          "md5": "f41776f49e5fcf9456ad2892d0bf24cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.osgi",
          "module": "osgi.core",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "p2api-0.0.4.jar",
          "url": "p2api-0.0.4.jar",
          "size": 3912,
          "sha512": "d0617b2c5f28b8712f93ba683a6729b61dd675fb07ca8c4e9ff8a14c68f32d2d06d66591576221a663cf9b021aa0864aff44cab65674e2c8dfcc2f836e0a4bbd",
          "sha256": "9a306a5bd7057204c92fb1af6606e82cd249b3aa058fd1f7514ae03337953a16",
          "sha1": "1d88a2fec9d351882872c94fd1edbd4f72128056",
          "md5": "f41776f49e5fcf9456ad2892d0bf24cf"
        }
      ]
    }
  ]
}
